src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20, unique=true)
     */
    private $sku;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    private $price;

    /**
     * @ORM\ManyToMany(targetEntity="Category", inversedBy="products")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="ProductFeature", mappedBy="product")
     */
    private $features;

    /**
     * @ORM\ManyToOne(targetEntity="Product", inversedBy="productModifications")
     * @ORM\JoinColumn(name="product_base_id", referencedColumnName="id")
     */
    private $productBase;

    /**
     * @ORM\OneToMany(targetEntity="Product", mappedBy="productBase")
     */
    private $productModifications;

    /**
     * Product constructor.
     */
    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->productModifications = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * @param mixed $sku
     */
    public function setSku($sku): void
    {
        $this->sku = $sku;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return (!$this->title && $this->getProductBase()) ? $this->getProductBase()->getTitle() : $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title): void
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getPrice()
    {
        return (!$this->price && $this->getProductBase()) ? $this->getProductBase()->getPrice() : $this->price;
    }

    /**
     * @param mixed $price
     */
    public function setPrice($price): void
    {
        $this->price = $price;
    }

    /**
     * @return mixed
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * @param mixed $categories
     */
    public function setCategories($categories): void
    {
        $this->categories = $categories;
    }

    /**
     * @return mixed
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     * @return mixed
     */
    public function getFeaturesByLang($lang)
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq("lang", $lang));
        return $this->features->matching($criteria);
    }

    /**
     * @param mixed $features
     */
    public function setFeatures($features): void
    {
        $this->features = $features;
    }

    /**
     * @return mixed
     */
    public function getProductBase()
    {
        return $this->productBase;
    }

    /**
     * @return mixed
     */
    public function getProductBaseView()
    {
        return ($this->getProductBase()) ? $this->getProductBase() : $this;
    }

    /**
     * @param mixed $productBase
     */
    public function setProductBase($productBase): void
    {
        $this->productBase = $productBase;
    }

    /**
     * @return mixed
     */
    public function getProductModifications()
    {
        return $this->productModifications;
    }

    /**
     * @param mixed $productModifications
     */
    public function setProductModifications($productModifications): void
    {
        $this->productModifications = $productModifications;
    }

}

templates/shop/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <ul>
    {% for product in products %}
        <li><a href="{{ path('product_detail', {sku: product.sku}) }}">{{ product.title }}</a></li>
    {% else %}
        Not products found
    {% endfor %}
    </ul>

{% endblock %}

templates/shop/product.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <p><a href="{{ path('product_list') }}"><< Product List</a></p>

    <h1 id="param-title">{{ product.title }}</h1>

    <ul>
        <li>SKU - <span id="param-sku">{{ product.sku }}</span></li>
        <li>Price - <span id="param-price">{{ product.price }}</span></li>
    </ul>

    {% if product.productBaseView.productModifications.count %}

        <h3>Product modifications:</h3>
        <select id="modifications">
            <option value="{{ product.productBaseView.sku }}">{{ product.productBaseView.title }}</option>
            {% for modification in product.productBaseView.productModifications %}
                <option {% if product.id == modification.id %}selected{% endif %} value="{{ modification.sku }}">{{ modification.title }}</option>
            {% endfor %}
        </select>

    {% endif %}

    {% if product.productBaseView.featuresByLang(lang).count %}
        <h3>Product features:</h3>
        <ul>
            {% for feature in product.productBaseView.featuresByLang(lang) %}
                <li>{{ feature.type }} - {{ feature.title }}</li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        var productApiUrl = '{{ path('product_detail_api', {sku: '__sku__'}) }}';
        var productUrl = '{{ path('product_detail', {sku: '__sku__'}) }}';
        $('#modifications').change(function () {
            var apiUrl = productApiUrl.replace(/__sku__/, $(this).val());
            var url = productUrl.replace(/__sku__/, $(this).val());
            $.ajax({
                url: apiUrl,
                dataType: 'json',
                success: function (data) {
                    for (var i in data) {
                        $('#param-' + i).text(data[i]);
                    }
                    window.history.pushState("", "", url);
                }
            });
        });
    </script>
{% endblock %}